### ISSUE TITLE
Session Error

### ISSUE THREAD

**Issue by kmasden** [jolicode/Harvest-Forecast-tools#5]
I have googled it and I think I have the correct packages installed and the .env file is setup correctly. Whenever I open the link I get the following:

A session must exist. Please use express-session middleware.
Error: A session must exist. Please use express-session middleware.
    at /Users/kentmasden/Documents/projects/Personal/Harvest-Forecast-tools-master/lib/storage/session.js:43:9
    at Layer.handle [as handle_request] (/Users/kentmasden/Documents/projects/Personal/Harvest-Forecast-tools-master/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/Users/kentmasden/Documents/projects/Personal/Harvest-Forecast-tools-master/node_modules/express/lib/router/index.js:317:13)
    at /Users/kentmasden/Documents/projects/Personal/Harvest-Forecast-tools-master/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/Users/kentmasden/Documents/projects/Personal/Harvest-Forecast-tools-master/node_modules/express/lib/router/index.js:335:12)
    at next (/Users/kentmasden/Documents/projects/Personal/Harvest-Forecast-tools-master/node_modules/express/lib/router/index.js:275:10)
    at session (/Users/kentmasden/Documents/projects/Personal/Harvest-Forecast-tools-master/node_modules/express-session/index.js:189:7)
    at Layer.handle [as handle_request] (/Users/kentmasden/Documents/projects/Personal/Harvest-Forecast-tools-master/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/Users/kentmasden/Documents/projects/Personal/Harvest-Forecast-tools-master/node_modules/express/lib/router/index.js:317:13)
    at /Users/kentmasden/Documents/projects/Personal/Harvest-Forecast-tools-master/node_modules/express/lib/router/index.js:284:7

Any help would be greatly appreciated.

**Comment by xavierlacot** [comment]
Hi @kmasden. You need to have a redis server running, it should fix the issue.
