### ISSUE TITLE
Compare Timesheets to Forecast Schedules is not working

### ISSUE THREAD

**Issue by kmasden** [jolicode/Harvest-Forecast-tools#6]
I am getting this error:

FAILED TypeError: Cannot read property 'harvest_id' of undefined
    at /Users/kentmasden/Documents/projects/Personal/Harvest-Forecast-tools-master/lib/reconcilier.js:139:26
    at arrayEach (/Users/kentmasden/Documents/projects/Personal/Harvest-Forecast-tools-master/node_modules/lodash/lodash.js:516:11)
    at Function.forEach (/Users/kentmasden/Documents/projects/Personal/Harvest-Forecast-tools-master/node_modules/lodash/lodash.js:9342:14)
    at /Users/kentmasden/Documents/projects/Personal/Harvest-Forecast-tools-master/lib/reconcilier.js:138:11
    at arrayEach (/Users/kentmasden/Documents/projects/Personal/Harvest-Forecast-tools-master/node_modules/lodash/lodash.js:516:11)
    at Function.forEach (/Users/kentmasden/Documents/projects/Personal/Harvest-Forecast-tools-master/node_modules/lodash/lodash.js:9342:14)
    at /Users/kentmasden/Documents/projects/Personal/Harvest-Forecast-tools-master/lib/reconcilier.js:118:7
    at arrayEach (/Users/kentmasden/Documents/projects/Personal/Harvest-Forecast-tools-master/node_modules/lodash/lodash.js:516:11)
    at Function.forEach (/Users/kentmasden/Documents/projects/Personal/Harvest-Forecast-tools-master/node_modules/lodash/lodash.js:9342:14)
    at reconcilier (/Users/kentmasden/Documents/projects/Personal/Harvest-Forecast-tools-master/lib/reconcilier.js:116:5)

When I try to compare the time sheets to the forecast. Any help would be appreciated.

**Comment by kmasden** [comment]
The Time Off Project in Forcast does not have a client Id or a harvest id and that seems to be causing the issue:

allocation
:
0
day
:
"2018-08-06"
id
:
15395708
notes
:
null
person_id
:
360778
project
:
client_id
:
null
harvest_id
:
null
name
:
"Time Off"
